name: Ubuntu-CI
on: [push, pull_request]

jobs:
  install-sdl2:
    runs-on: ubuntu-latest
    steps:
      - name: Install SDL2
        run: |
          sudo apt update
          sudo apt install libsdl2-dev

  build-qt6:
    needs:
      - install-sdl2
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Install QT6
       run: |
        sudo apt update
        sudo apt install qt6-base-dev
     - name: Build tworld2 (Qt6)
       run: |
         mkdir build-qt6 && cd build-qt6
         cmake -DCMAKE_BUILD_TYPE=Debug -DOSHW=qt \
           -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/dist-qt6 ..
         make -j2 && make install

  build-qt5:
    needs:
      - install-sdl2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install QT5
        run: |
          sudo apt update
          sudo apt install qtbase5-dev
      - name: Build tworld2 (Qt5)
        run: |
          mkdir build-qt5 && cd build-qt5
          cmake -DCMAKE_BUILD_TYPE=Debug -DOSHW=qt \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/dist-qt5 ..
          make -j2 && make install

  build-sdl1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SDL1
        run: |
          sudo apt update
          sudo apt install libsdl1.2-dev
      - name: Build tworld (SDL)
        run: |
          mkdir build-sdl && cd build-sdl
          cmake -DCMAKE_BUILD_TYPE=Debug -DOSHW=sdl \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/dist-sdl ..
          make -j2 && make install